library(dplyr)
library(datasets)
hpc <- read.table("household_power_consumption.txt",sep = ";",header=TRUE)
hpc$Date <- as.Date(hpc$Date,"%d/%m/%Y")
hpc <- filter(hpc,Date=="2007-02-01"| Date=="2007-02-02")
datetime <- as.POSIXct(paste(hpc$Date, hpc$Time),format="%Y-%m-%d %H:%M:%S")
hpc <- cbind(hpc,datetime)
hpc$Sub_metering_1 <- as.numeric(hpc$Sub_metering_1)
hpc$Sub_metering_2 <- as.numeric(hpc$Sub_metering_2)
hpc$Sub_metering_3 <- as.numeric(hpc$Sub_metering_3)
with(hpc,plot(x=datetime,y=Sub_metering_1,type="l",ylab="Energy sub metering",col="black"))
lines(x=datetime,y=hpc$Sub_metering_2,type="l",col="red")
lines(x=datetime,y=hpc$Sub_metering_3,type="l",col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file="plot3.png",width = 480, height = 480)
dev.off()
