library(dplyr)
library(datasets)
hpc <- read.table("household_power_consumption.txt",sep = ";",header=TRUE)
hpc$Date <- as.Date(hpc$Date,"%d/%m/%Y")
hpc <- filter(hpc,Date=="2007-02-01"| Date=="2007-02-02")
datetime <- as.POSIXct(paste(hpc$Date, hpc$Time),format="%Y-%m-%d %H:%M:%S")
hpc <- cbind(hpc,datetime)
hpc$Sub_metering_1 <- as.numeric(hpc$Sub_metering_1)
hpc$Sub_metering_2 <- as.numeric(hpc$Sub_metering_2)
hpc$Sub_metering_3 <- as.numeric(hpc$Sub_metering_3)
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc$Global_reactive_power <- as.numeric(hpc$Global_reactive_power)
hpc$Voltage <- as.numeric(hpc$Voltage)
par(mfrow=c(2,2))
with(hpc,{
  plot(x=datetime,y=Global_active_power,type="l",ylab = "Global Active Power (kilowatts)")
  plot(x=datetime,y=Voltage,type="l",ylab = "Voltage")
  plot(x=datetime,y=Sub_metering_1,type="l",ylab="Energy sub metering",col="black")
lines(x=datetime,y=hpc$Sub_metering_2,type="l",col="red")
lines(x=datetime,y=hpc$Sub_metering_3,type="l",col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(x=datetime,y=Global_reactive_power,type="l")
})
dev.copy(png, file="plot4.png",width = 480, height = 480)
dev.off()
